# Generated by Django 3.0.3 on 2020-04-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='category',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('NonFunctional', 'Non functional')], max_length=14),
        ),
        migrations.AddField(
            model_name='requirement',
            name='choose',
            field=models.CharField(blank=True, choices=[('UserRequirement', 'User Requirement'), ('SystemRequirement', 'System Requirement')], max_length=18),
        ),
    ]
