# Generated by Django 3.0.3 on 2020-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_requirement_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('NonFunctional', 'Non functional')], max_length=14),
        ),
    ]
