# Generated by Django 3.0.3 on 2020-04-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200429_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='reply',
        ),
        migrations.AddField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.Requirement'),
        ),
    ]
