# Generated by Django 3.0.3 on 2020-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='choose',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.CharField(blank=True, choices=[('SF', 'System Functional'), ('SNF', 'System Non-functional'), ('UR', 'User Requirement')], max_length=14),
        ),
    ]
