# Generated by Django 3.0.3 on 2020-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200430_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='parent',
            new_name='reply',
        ),
    ]
