# Generated by Django 3.0.3 on 2020-04-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200430_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='reply',
        ),
    ]
