# Generated by Django 3.0.3 on 2020-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200531_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.CharField(blank=True, choices=[('Choose', 'Choose'), ('Functional System', 'Functional System'), ('Non-functional System', 'Non-functional System'), ('User Requirement', 'User Requirement')], default='Choose', max_length=30),
        ),
    ]
