# Generated by Django 3.0.3 on 2020-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200531_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.CharField(choices=[('', '--- Choose Requirement Category ---'), ('Functional System', 'Functional System'), ('Non-functional System', 'Non-functional System'), ('User Requirement', 'User Requirement')], default='', max_length=30),
        ),
    ]
