# Generated by Django 3.0.3 on 2020-06-09 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20200608_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='requirement',
            name='reqdislikes',
            field=models.ManyToManyField(blank=True, related_name='reqdislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirement',
            name='reqlikes',
            field=models.ManyToManyField(blank=True, related_name='reqlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
